# Generated by Django 6.0.6 on 2026-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อ-นามสกุล")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="สถานะใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "นักศึกษา",
                "verbose_name_plural": "นักศึกษาทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
