# Generated by Django 6.0.6 on 2026-09-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year_level",
            field=models.PositiveIntegerField(default=2, verbose_name="ชั้นปี"),
        ),
    ]
