# Generated by Django 6.0.6 on 2026-09-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_add_year_level_to_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(default="student", max_length=20)),
                ("identifier", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("otp", models.CharField(max_length=10)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="ชื่อผู้ใช้"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="อีเมล"),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=128, verbose_name="รหัสผ่าน (Hash)"),
                ),
                (
                    "password_plain",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="รหัสผ่าน (Plain)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="สถานะใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "บุคลากร",
                "verbose_name_plural": "บุคลากรทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="password_hash",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="รหัสผ่าน (Hash)"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="password_plain",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="รหัสผ่าน (Plain)"
            ),
        ),
    ]
