# Generated by Django 6.0.6 on 2026-09-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_add_user_account_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_id",
                    models.IntegerField(unique=True, verbose_name="รหัสอาคาร"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="ชื่ออาคาร (ไทย)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ชื่ออาคาร (อังกฤษ)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="academic", max_length=50, verbose_name="หมวดหมู่"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="รหัสย่อ"),
                ),
                ("coord_x", models.FloatField(default=0, verbose_name="พิกัดแผนที่ X")),
                ("coord_y", models.FloatField(default=0, verbose_name="พิกัดแผนที่ Y")),
                (
                    "lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude GPS"
                    ),
                ),
                (
                    "lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude GPS"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="รายละเอียด")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="เบอร์โทร"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="แท็กค้นหา"),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="รูปภาพอาคาร"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "อาคาร",
                "verbose_name_plural": "อาคารทั้งหมด",
                "ordering": ["building_id"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="รหัสผู้ใช้")),
                ("user_name", models.CharField(max_length=255, verbose_name="ชื่อผู้ใช้")),
                ("role", models.CharField(max_length=50, verbose_name="บทบาท")),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, verbose_name="อีเมล"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="IP Address"
                    ),
                ),
                (
                    "device",
                    models.CharField(blank=True, max_length=255, verbose_name="อุปกรณ์"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันเวลา"),
                ),
            ],
            options={
                "verbose_name": "ประวัติกิจกรรมผู้ใช้",
                "verbose_name_plural": "ประวัติกิจกรรมผู้ใช้ทั้งหมด",
                "ordering": ["-timestamp"],
            },
        ),
    ]
