# Generated by Django 6.0.6 on 2026-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_add_building_and_activity_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffuser",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="อนุมัติแล้ว"),
        ),
    ]
